### ISSUE TITLE
Insufficient privileges to get access token for app *

### ISSUE THREAD

**Issue by detiam** [Lanzador/merge-dd#1]
Found this repo when I trying to workround error "Insufficient privileges to get access token for app *" "Depot * not listed for app *", so there you solve it. Thank you so much!

but it doesn't seems work on newer version?
<details>
<summary>Compiled version (Merge + No app token)</summary>
<pre><code>PS G:\Steam\Compiled version (Merge + No app token)> .\DepotDownloader.exe -depotkeys .\steam.key -app 1468810 -depot 1468811 -manifest 8441731543048780397
Using depot keys from '.\steam.key'.
No username given. Using anonymous account with dedicated server subscription.
Connecting to Steam3... Done!
Logging anonymously into Steam3... Done!
Using Steam3 suggested CellID: 2
Insufficient privileges to get access token for app 1468810
Will try to use app token given in the parameter.
Got AppInfo for 1468810
Using app branch: 'Public'.
Processing depot 1468811 -
Downloading depot manifest... Done!
Manifest 8441731543048780397 (2022/4/29 10:08:16)
Downloading depot 1468811 -
Pre-allocating depots\1468811 ()\0\GameAssembly.dll
Pre-allocating depots\1468811 ()\0\UnityPlayer.dll
......
 99.94% depots\1468811 ()\0\guigubahuang_Data\globalgamemanagers.assets
 99.94% depots\1468811 ()\0\guigubahuang_Data\il2cpp_data\etc\mono\4.5\DefaultWsdlHelpGenerator.aspx
 99.94% depots\1468811 ()\0\guigubahuang_Data\sharedassets0.assets
100.00% depots\1468811 ()\0\guigubahuang_Data\sharedassets0.assets.resS
100.00% depots\1468811 ()\0\guigubahuang_Data\sharedassets1.assets
100.00% depots\1468811 ()\0\guigubahuang_Data\sharedassets2.assets
Depot 1468811 - Downloaded 0 bytes (0 bytes uncompressed)
Total downloaded: 0 bytes (0 bytes uncompressed) from 1 depots
Disconnected from Steam
</code></pre>
</details>

<details>
<summary>Compiled version (Edit #4)</summary>
<pre><code>PS G:\Steam\Compiled version (Edit #4)> .\DepotDownloader.exe -depotkeys .\steam.key -app 1468810 -depot 1468811 -manifest 8441731543048780397
Using depot keys from '.\steam.key'.
No username given. Using anonymous account with dedicated server subscription.
Connecting to Steam3... Done!
Logging anonymously into Steam3... Done!
Using Steam3 suggested CellID: 2
Insufficient privileges to get access token for app 1468810
Got AppInfo for 1468810
Using app branch: 'Public'.
Depot 1468811 not listed for app 1468810
Disconnected from Steam
</code></pre>
</details>

and I really want to know about what `-apptoken`,`-delta-manifest` is and what for, google isn't give me answer, it's for workshop? tell me more details please🙏🏻

**Comment by Lanzador** [comment]
Hey.
First, you're talking about the other repo, I don't know why you created the issue _here_.
Second, "Edit #4" isn't really a "newer version", it's the same thing, just without the app token workaround.
Third, `-apptoken` is for entering the app token if you have it, but that's not really needed anymore since the workaround exists. And `-delta-manifest` is for entering the old manifest ID if you want to update from a specific already installed version. Normally, DD stores the old manifest ID, but this may be useful if you delete the config file or ruin it (e. g. `-manifest-only` updates the ID stored there).
I don't come here that often, so if you have any further questions, it's preferred that you contact me on Discord: `Alexander886GF#5248`.
